version: '3.6'
services:
  hello_world_miniserver:
    image: hello_world_server:part_5
    build:
      context: .
      dockerfile: Dockerfile_5
  nginx_x:
    image: nginx
    volumes:
      - ./part_6/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:8080